---
title: Homo Journalius
timezone: UTC
collections:
  anker:
    title: Anker
    output: true
    permalink: "/anker/:title/"
  posts:
    title: Posts
    output: true
  set:
    title: Set
    output: true
    permalink: "/set/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
- scope:
    path: decor
  values:
    layout: decor
- scope:
    path: anker
  values:
    layout: anker
email: homo.journalius@gmail.com
description: Homo Journalius kijkt met grote ogen naar Het Journaal
baseurl: 
url: 
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- artwork
- bower_components/jquery/src
- bash.sh
- gulpfile.js
sass:
  sass_dir: _sass
google:
  tag_manager:
    container_id: GTM-P6Z548D
